service: firebase-replication
runtime: python27
threadsafe: True
api_version: 1
#version: 1

instance_class: F2
automatic_scaling:
  max_pending_latency: 4000ms
  target_cpu_utilization: 0.9
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80  
  
  
  
handlers:
- url: /.*
  script: boots_main.app
  login: admin
  
env_variables:
 FIREBASE_URL: https://aqueous-choir-160420.firebaseio.com
 FIREBASE_KEY: gAC4yyNSgBBzWWS8yStc6Qx7H4fkpmUlq1EqzK25
 FIREBASE_DOMAIN: aqueous-choir-160420.firebaseapp.com
 FIREBASE_ID: 123